# Generated by Django 5.2.5 on 2025-08-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fileName', models.CharField(max_length=255)),
                ('uploader', models.CharField(max_length=255)),
                ('file_data', models.BinaryField(blank=True, null=True)),
                ('file_url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'business_data',
            },
        ),
        migrations.CreateModel(
            name='ProcessedReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(default='basic_analysis', max_length=100)),
                ('processed_data', models.JSONField()),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('ppt_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessdata')),
            ],
            options={
                'db_table': 'processed_reports',
            },
        ),
    ]
