# Generated by Django 5.2.5 on 2025-08-14 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_businessdata_processedreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
