# Generated by Django 5.2.5 on 2025-08-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_businessdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdata',
            name='file_data',
        ),
    ]
