# Generated by Django 4.2.4 on 2025-08-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_businessdata_file_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('department_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.TimeField()),
                ('meeting_location', models.CharField(max_length=255)),
                ('meeting_mic1', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_mic2', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_mic3', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_department', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_participant', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('meeting_file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meeting_summary', models.CharField(max_length=255)),
                ('meeting_org', models.FileField(upload_to='')),
                ('ind_file1', models.FileField(blank=True, null=True, upload_to='')),
                ('ind_file2', models.FileField(blank=True, null=True, upload_to='')),
                ('ind_file3', models.FileField(blank=True, null=True, upload_to='')),
                ('uploaded_date', models.DateField(blank=True, null=True)),
                ('uploaded_time', models.TimeField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('updated_time', models.TimeField(blank=True, null=True)),
                ('meeting_transcripts', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.meeting')),
            ],
            options={
                'db_table': 'meeting_files',
            },
        ),
    ]
