# Generated by Django 4.2.4 on 2025-08-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_department_employee_meeting_meetingfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='uploader',
            field=models.ForeignKey(db_column='uploader', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
