# Generated by Django 4.2.4 on 2025-08-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_businessdata_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='uploader',
            field=models.CharField(max_length=255),
        ),
    ]
