# Generated by Django 5.2.5 on 2025-08-21 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_businessdata_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='uploader',
            field=models.ForeignKey(db_column='uploader', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_content', models.JSONField()),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.businessdata')),
            ],
            options={
                'db_table': 'userComment_data',
            },
        ),
    ]
