# Generated by Django 4.2.4 on 2025-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_businessdata_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='task_content',
            field=models.TextField(default='No content provided'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='Untitled Task', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='urgent_level',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='uploader',
            field=models.ForeignKey(db_column='uploader', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
