# Generated by Django 4.2.4 on 2025-08-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_businessdata_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='uploader',
            field=models.ForeignKey(db_column='uploader', on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateField()),
                ('complaint_audio', models.CharField(max_length=255)),
                ('complaint_transcript', models.TextField()),
                ('complaint_summary', models.TextField()),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
            options={
                'db_table': 'Complaint',
            },
        ),
    ]
