# Generated by Django 5.2.5 on 2025-08-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_businessdata_uploader_commentreport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentreport',
            table='comment_reports',
        ),
    ]
