# Generated by Django 4.2.4 on 2025-08-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_task_options_remove_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
