# Generated by Django 5.2.5 on 2025-08-21 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_commentreport_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentreport',
            table='userComment_data',
        ),
    ]
