# Generated by Django 4.2.4 on 2025-08-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_businessdata_uploader_complaint'),
        ('api', '0009_alter_task_table'),
        ('api', '0010_alter_commentreport_table'),
    ]

    operations = [
    ]
